version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: banking-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking -d banking"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: banking-adminer
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8090:8080"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    restart: always

volumes:
  pgdata:
  keycloak_data: