server:
  port: 8080

spring:
  application:
    name: banking-mvp
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: banking
    password: banking
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.default_schema: public
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
