server:
  port: 8080
  # Never expose server internals in exceptions
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

spring:
  application:
    name: banking-mvp
  security:
    oauth2:
      resourceserver:
        jwt:
          # 👇 Use your realm’s OIDC issuer URL (check Realm settings → OpenID Endpoint Configuration)
          issuer-uri: http://localhost:8081/realms/BankingApp
          # or alternatively:
          # jwk-set-uri: http://localhost:8081/realms/BankingApp/protocol/openid-connect/certs

  # Custom property we use in SecurityConfig to validate audience
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: banking
    password: banking
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.default_schema: public
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
# Custom property we use in SecurityConfig to validate audience
app:
  security:
    expected-audience: Angular-Banking-App,Banking-App
    client-roles:
      clients: Angular-Banking-App,Banking-App

springdoc:
  swagger-ui:
    oauth:
      client-id: Banking-App
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html